"""Render every gen_*.py to src/neurosync/assets/ambience/<id>.ogg + catalog.json.

    python tools/ambience/build.py [--only id ...]      (requires: pip install -e ".[assets]")
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import analyze  # noqa: E402
import common  # noqa: E402

OUT = Path(__file__).resolve().parents[2] / "src" / "neurosync" / "assets" / "ambience"
LICENSE = "CC0-1.0 (procedurally generated by tools/ambience, no third-party samples)"


def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--only", nargs="*")
    a = ap.parse_args()
    mods = []
    for p in sorted(Path(__file__).parent.glob("gen_*.py")):
        mod = analyze.load_gen(p.stem[4:].replace("_", "-"))
        if not a.only or mod.META["id"] in a.only:
            mods.append(mod)
    mods.sort(key=lambda m: m.META.get("order", 99))
    OUT.mkdir(parents=True, exist_ok=True)
    catalog, failed = [], []
    for mod in mods:
        meta = mod.META
        rep = analyze.analyze(mod, None, png=False)
        if not rep["pass"]:
            failed.append((meta["id"], rep["failures"])); continue
        raw = common.encode_ogg(analyze.render(mod))
        (OUT / f"{meta['id']}.ogg").write_bytes(raw)
        catalog.append({"id": meta["id"], "name": meta["name"], "file": f"{meta['id']}.ogg",
                        "category": meta["category"], "description": meta["description"],
                        "loop_xfade_s": meta["loop_xfade_s"], "default_volume": meta["default_volume"],
                        "duration_s": meta["duration_s"], "license": LICENSE})
        print(f"built {meta['id']:<14} {len(raw) / 1e3:6.0f} kB")
    if failed:
        for gid, why in failed:
            print("FAILED", gid, why)
        return 1
    # catalog.json lists exactly what exists on disk (all gens, not only --only)
    existing = {c["id"]: c for c in json.loads((OUT / "catalog.json").read_text())} if (OUT / "catalog.json").exists() else {}
    existing.update({c["id"]: c for c in catalog})
    order = {m.META["id"]: m.META.get("order", 99) for m in (analyze.load_gen(p.stem[4:].replace("_", "-"))
             for p in Path(__file__).parent.glob("gen_*.py"))}
    final = sorted((c for c in existing.values() if c["id"] in order), key=lambda c: order[c["id"]])
    (OUT / "catalog.json").write_text(json.dumps(final, indent=2) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
